server:
  port: 1337
  contextPath: /darts

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver: org.h2.Driver
    username: sa
    password:
    hibernateDialect: org.hibernate.dialect.MySQL5Dialect